const fs = require('fs')

/**
 * Return a string generated by diceware.
 */
function dadoware (array) {
  let obj = JSON.parse(fs.readFileSync('./palavras.json', 'utf8'))
  let result = ''
  for (let i = 0; i < array.length; i++)
    result += `${obj[array[i]]} `

  return result
}

module.exports = dadoware
